/* The following code was generated by JFlex 1.4.3 on 12.04.12 12:53 */

package haw.ai.ci;

import static haw.ai.ci.TokenID.*;



/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.4.3
 * on 12.04.12 12:53 from the specification file
 * <tt>/home/felix/workspace/CI-SS12-FSTT/input/grammar.flex</tt>
 */
public class MyScanner {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0, 0
  };

  /** 
   * Translates characters to character classes
   */
  private static final String ZZ_CMAP_PACKED = 
    "\11\0\1\5\1\5\2\0\1\5\22\0\1\5\2\0\1\14\4\0"+
    "\1\21\1\22\1\6\1\7\1\20\1\10\1\17\1\11\12\1\1\12"+
    "\1\25\1\15\1\13\1\16\2\0\1\45\1\52\1\50\1\34\1\32"+
    "\1\27\1\53\1\31\1\37\2\2\1\41\1\54\1\33\1\26\1\35"+
    "\1\2\1\36\1\42\1\30\1\46\1\51\1\43\1\2\1\47\1\2"+
    "\1\23\1\0\1\24\1\0\1\3\1\0\1\40\1\52\1\50\1\34"+
    "\1\44\1\27\1\53\1\31\1\37\2\2\1\41\1\54\1\33\1\26"+
    "\1\35\1\2\1\36\1\42\1\30\1\46\1\51\1\43\1\2\1\47"+
    "\1\2\2\0\1\4\uff82\0";

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = zzUnpackCMap(ZZ_CMAP_PACKED);

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\0\1\1\1\2\1\3\1\4\1\5\1\6\1\7"+
    "\1\10\1\11\1\12\1\13\1\14\1\15\1\16\1\17"+
    "\1\20\1\21\1\22\1\23\1\24\16\3\1\0\1\25"+
    "\1\26\1\27\1\30\4\3\1\31\2\3\1\32\11\3"+
    "\1\33\12\3\1\34\2\3\1\35\1\36\1\37\4\3"+
    "\1\40\7\3\1\41\1\3\1\42\2\3\1\43\1\44"+
    "\1\45\1\46\1\47\2\3\1\50\1\51\1\52\2\3"+
    "\1\53";

  private static int [] zzUnpackAction() {
    int [] result = new int[104];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\55\0\132\0\207\0\55\0\55\0\55\0\55"+
    "\0\55\0\264\0\55\0\55\0\341\0\u010e\0\55\0\55"+
    "\0\55\0\55\0\55\0\55\0\55\0\u013b\0\u0168\0\u0195"+
    "\0\u01c2\0\u01ef\0\u021c\0\u0249\0\u0276\0\u02a3\0\u02d0\0\u02fd"+
    "\0\u032a\0\u0357\0\u0384\0\u03b1\0\55\0\55\0\55\0\207"+
    "\0\u03de\0\u040b\0\u0438\0\u0465\0\207\0\u0492\0\u04bf\0\207"+
    "\0\u04ec\0\u0519\0\u0546\0\u0573\0\u05a0\0\u05cd\0\u05fa\0\u0627"+
    "\0\u0654\0\207\0\u0681\0\u06ae\0\u06db\0\u0708\0\u0735\0\u0762"+
    "\0\u078f\0\u07bc\0\u07e9\0\u0816\0\207\0\u0843\0\u0870\0\207"+
    "\0\207\0\207\0\u089d\0\u08ca\0\u08f7\0\u0924\0\207\0\u0951"+
    "\0\u097e\0\u09ab\0\u09d8\0\u0a05\0\u0a32\0\u0a5f\0\207\0\u0a8c"+
    "\0\207\0\u0ab9\0\u0ae6\0\207\0\207\0\207\0\207\0\207"+
    "\0\u0b13\0\u0b40\0\207\0\207\0\207\0\u0b6d\0\u0b9a\0\207";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[104];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\2\1\3\1\4\2\2\1\5\1\6\1\7\1\10"+
    "\1\11\1\12\1\13\1\14\1\15\1\16\1\17\1\20"+
    "\1\21\1\22\1\23\1\24\1\25\1\26\1\4\1\27"+
    "\1\4\1\30\1\4\1\31\1\32\1\33\1\34\1\35"+
    "\2\4\1\36\1\30\1\35\1\37\1\4\1\40\1\41"+
    "\1\42\1\4\1\43\56\0\1\3\54\0\2\4\1\44"+
    "\22\0\27\4\13\0\1\45\54\0\1\46\54\0\1\47"+
    "\42\0\2\4\1\44\22\0\1\4\1\50\25\4\1\0"+
    "\2\4\1\44\22\0\3\4\1\51\15\4\1\52\5\4"+
    "\1\0\2\4\1\44\22\0\5\4\1\53\5\4\1\54"+
    "\13\4\1\0\2\4\1\44\22\0\1\55\26\4\1\0"+
    "\2\4\1\44\22\0\10\4\1\56\16\4\1\0\2\4"+
    "\1\44\22\0\4\4\1\57\11\4\1\57\10\4\1\0"+
    "\2\4\1\44\22\0\1\4\1\60\25\4\1\0\2\4"+
    "\1\44\22\0\10\4\1\61\16\4\1\0\2\4\1\44"+
    "\22\0\3\4\1\62\23\4\1\0\2\4\1\44\22\0"+
    "\5\4\1\63\21\4\1\0\2\4\1\44\22\0\1\64"+
    "\26\4\1\0\2\4\1\44\22\0\12\4\1\65\4\4"+
    "\1\65\7\4\1\0\2\4\1\44\22\0\4\4\1\66"+
    "\11\4\1\66\10\4\1\0\2\4\1\44\22\0\1\67"+
    "\26\4\4\0\1\4\51\0\2\4\1\44\22\0\4\4"+
    "\1\70\11\4\1\70\10\4\1\0\2\4\1\44\22\0"+
    "\7\4\1\71\17\4\1\0\2\4\1\44\22\0\6\4"+
    "\1\72\20\4\1\0\2\4\1\44\22\0\14\4\1\73"+
    "\12\4\1\0\2\4\1\44\22\0\1\74\10\4\1\75"+
    "\15\4\1\0\2\4\1\44\22\0\7\4\1\76\2\4"+
    "\1\77\4\4\1\77\2\4\1\100\4\4\1\0\2\4"+
    "\1\44\22\0\10\4\1\101\16\4\1\0\2\4\1\44"+
    "\22\0\11\4\1\102\15\4\1\0\2\4\1\44\22\0"+
    "\2\4\1\103\24\4\1\0\2\4\1\44\22\0\5\4"+
    "\1\104\21\4\1\0\2\4\1\44\22\0\10\4\1\105"+
    "\16\4\1\0\2\4\1\44\22\0\25\4\1\106\1\4"+
    "\1\0\2\4\1\44\22\0\6\4\1\107\20\4\1\0"+
    "\2\4\1\44\22\0\5\4\1\110\21\4\1\0\2\4"+
    "\1\44\22\0\4\4\1\111\11\4\1\111\10\4\1\0"+
    "\2\4\1\44\22\0\4\4\1\112\4\4\1\113\4\4"+
    "\1\112\10\4\1\0\2\4\1\44\22\0\22\4\1\114"+
    "\4\4\1\0\2\4\1\44\22\0\5\4\1\115\21\4"+
    "\1\0\2\4\1\44\22\0\4\4\1\116\11\4\1\116"+
    "\10\4\1\0\2\4\1\44\22\0\6\4\1\117\20\4"+
    "\1\0\2\4\1\44\22\0\1\120\26\4\1\0\2\4"+
    "\1\44\22\0\12\4\1\121\4\4\1\121\7\4\1\0"+
    "\2\4\1\44\22\0\13\4\1\122\13\4\1\0\2\4"+
    "\1\44\22\0\11\4\1\123\15\4\1\0\2\4\1\44"+
    "\22\0\14\4\1\124\12\4\1\0\2\4\1\44\22\0"+
    "\11\4\1\125\15\4\1\0\2\4\1\44\22\0\20\4"+
    "\1\126\6\4\1\0\2\4\1\44\22\0\1\4\1\127"+
    "\25\4\1\0\2\4\1\44\22\0\4\4\1\130\11\4"+
    "\1\130\10\4\1\0\2\4\1\44\22\0\2\4\1\131"+
    "\24\4\1\0\2\4\1\44\22\0\16\4\2\132\7\4"+
    "\1\0\2\4\1\44\22\0\10\4\1\133\16\4\1\0"+
    "\2\4\1\44\22\0\21\4\1\134\5\4\1\0\2\4"+
    "\1\44\22\0\4\4\1\135\11\4\1\135\10\4\1\0"+
    "\2\4\1\44\22\0\13\4\1\136\13\4\1\0\2\4"+
    "\1\44\22\0\2\4\1\137\24\4\1\0\2\4\1\44"+
    "\22\0\5\4\1\140\21\4\1\0\2\4\1\44\22\0"+
    "\13\4\1\141\13\4\1\0\2\4\1\44\22\0\6\4"+
    "\1\142\20\4\1\0\2\4\1\44\22\0\2\4\1\143"+
    "\24\4\1\0\2\4\1\44\22\0\6\4\1\144\20\4"+
    "\1\0\2\4\1\44\22\0\4\4\1\145\11\4\1\145"+
    "\10\4\1\0\2\4\1\44\22\0\20\4\1\146\6\4"+
    "\1\0\2\4\1\44\22\0\10\4\1\147\16\4\1\0"+
    "\2\4\1\44\22\0\4\4\1\150\11\4\1\150\10\4";

  private static int [] zzUnpackTrans() {
    int [] result = new int[3015];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unkown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\0\1\11\2\1\5\11\1\1\2\11\2\1\7\11"+
    "\16\1\1\0\3\11\101\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[104];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn;

  /** 
   * zzAtBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;


  /**
   * Creates a new scanner
   * There is also a java.io.InputStream version of this constructor.
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public MyScanner(java.io.Reader in) {
    this.zzReader = in;
  }

  /**
   * Creates a new scanner.
   * There is also java.io.Reader version of this constructor.
   *
   * @param   in  the java.io.Inputstream to read input from.
   */
  public MyScanner(java.io.InputStream in) {
    this(new java.io.InputStreamReader(in));
  }

  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] zzUnpackCMap(String packed) {
    char [] map = new char[0x10000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 168) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }


  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead-zzStartRead);

      /* translate stored positions */
      zzEndRead-= zzStartRead;
      zzCurrentPos-= zzStartRead;
      zzMarkedPos-= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzCurrentPos*2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
    }

    /* finally: fill the buffer with new input */
    int numRead = zzReader.read(zzBuffer, zzEndRead,
                                            zzBuffer.length-zzEndRead);

    if (numRead > 0) {
      zzEndRead+= numRead;
      return false;
    }
    // unlikely but not impossible: read 0 characters, but not at end of stream    
    if (numRead == 0) {
      int c = zzReader.read();
      if (c == -1) {
        return true;
      } else {
        zzBuffer[zzEndRead++] = (char) c;
        return false;
      }     
    }

	// numRead < 0
    return true;
  }

    
  /**
   * Closes the input stream.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true;            /* indicate end of file */
    zzEndRead = zzStartRead;  /* invalidate buffer    */

    if (zzReader != null)
      zzReader.close();
  }


  /**
   * Resets the scanner to read from a new input stream.
   * Does not close the old reader.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>ZZ_INITIAL</tt>.
   *
   * @param reader   the new input stream 
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzAtBOL  = true;
    zzAtEOF  = false;
    zzEOFDone = false;
    zzEndRead = zzStartRead = 0;
    zzCurrentPos = zzMarkedPos = 0;
    yyline = yychar = yycolumn = 0;
    zzLexicalState = YYINITIAL;
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final String yytext() {
    return new String( zzBuffer, zzStartRead, zzMarkedPos-zzStartRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer[zzStartRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public Token yylex() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char [] zzBufferL = zzBuffer;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      boolean zzR = false;
      for (zzCurrentPosL = zzStartRead; zzCurrentPosL < zzMarkedPosL;
                                                             zzCurrentPosL++) {
        switch (zzBufferL[zzCurrentPosL]) {
        case '\u000B':
        case '\u000C':
        case '\u0085':
        case '\u2028':
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn++;
        }
      }

      if (zzR) {
        // peek one character ahead if it is \n (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof) 
            zzPeek = false;
          else 
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;
  
      zzState = ZZ_LEXSTATE[zzLexicalState];


      zzForAction: {
        while (true) {
    
          if (zzCurrentPosL < zzEndReadL)
            zzInput = zzBufferL[zzCurrentPosL++];
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = zzBufferL[zzCurrentPosL++];
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          int zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
        case 23: 
          { new Token(HIEQ, yytext(), yyline, yycolumn);
          }
        case 44: break;
        case 9: 
          { new Token(COLON, yytext(), yyline, yycolumn);
          }
        case 45: break;
        case 28: 
          { new Token(VAR, yytext(), yyline, yycolumn);
          }
        case 46: break;
        case 14: 
          { new Token(DOT, yytext(), yyline, yycolumn);
          }
        case 47: break;
        case 34: 
          { new Token(PRINT, yytext(), yyline, yycolumn);
          }
        case 48: break;
        case 41: 
          { new Token(RECORD, yytext(), yyline, yycolumn);
          }
        case 49: break;
        case 33: 
          { new Token(ELSIF, yytext(), yyline, yycolumn);
          }
        case 50: break;
        case 42: 
          { new Token(MODULE, yytext(), yyline, yycolumn);
          }
        case 51: break;
        case 17: 
          { new Token(RPAR, yytext(), yyline, yycolumn);
          }
        case 52: break;
        case 32: 
          { new Token(READ, yytext(), yyline, yycolumn);
          }
        case 53: break;
        case 31: 
          { new Token(ELSE, yytext(), yyline, yycolumn);
          }
        case 54: break;
        case 15: 
          { new Token(COMMA, yytext(), yyline, yycolumn);
          }
        case 55: break;
        case 30: 
          { new Token(TYPE, yytext(), yyline, yycolumn);
          }
        case 56: break;
        case 13: 
          { new Token(HI, yytext(), yyline, yycolumn);
          }
        case 57: break;
        case 35: 
          { new Token(ARRAY, yytext(), yyline, yycolumn);
          }
        case 58: break;
        case 6: 
          { new Token(PLUS, yytext(), yyline, yycolumn);
          }
        case 59: break;
        case 21: 
          { new Token(ASSIGN, yytext(), yyline, yycolumn);
          }
        case 60: break;
        case 18: 
          { new Token(LBRAC, yytext(), yyline, yycolumn);
          }
        case 61: break;
        case 38: 
          { new Token(CONST, yytext(), yyline, yycolumn);
          }
        case 62: break;
        case 24: 
          { new Token(OF, yytext(), yyline, yycolumn);
          }
        case 63: break;
        case 2: 
          { System.out.println("DIGITS " + yytext());
          }
        case 64: break;
        case 29: 
          { new Token(THEN, yytext(), yyline, yycolumn);
          }
        case 65: break;
        case 8: 
          { new Token(DIV, yytext(), yyline, yycolumn);
          }
        case 66: break;
        case 19: 
          { new Token(RBRAC, yytext(), yyline, yycolumn);
          }
        case 67: break;
        case 7: 
          { new Token(MINUS, yytext(), yyline, yycolumn);
          }
        case 68: break;
        case 1: 
          { System.out.println("error (" + yytext() + "," + yyline + "," +  yycolumn +")"); System.exit(0);
          }
        case 69: break;
        case 10: 
          { new Token(EQ, yytext(), yyline, yycolumn);
          }
        case 70: break;
        case 25: 
          { new Token(DO, yytext(), yyline, yycolumn);
          }
        case 71: break;
        case 3: 
          { System.out.println("ID " + yytext());
          }
        case 72: break;
        case 40: 
          { new Token(REPEAT, yytext(), yyline, yycolumn);
          }
        case 73: break;
        case 37: 
          { new Token(UNTIL, yytext(), yyline, yycolumn);
          }
        case 74: break;
        case 26: 
          { new Token(IF, yytext(), yyline, yycolumn);
          }
        case 75: break;
        case 16: 
          { new Token(LPAR, yytext(), yyline, yycolumn);
          }
        case 76: break;
        case 36: 
          { new Token(WHILE, yytext(), yyline, yycolumn);
          }
        case 77: break;
        case 27: 
          { new Token(END, yytext(), yyline, yycolumn);
          }
        case 78: break;
        case 39: 
          { new Token(BEGIN, yytext(), yyline, yycolumn);
          }
        case 79: break;
        case 43: 
          { new Token(PROCEDURE, yytext(), yyline, yycolumn);
          }
        case 80: break;
        case 22: 
          { new Token(LOEQ, yytext(), yyline, yycolumn);
          }
        case 81: break;
        case 12: 
          { new Token(LO, yytext(), yyline, yycolumn);
          }
        case 82: break;
        case 5: 
          { new Token(MUL, yytext(), yyline, yycolumn);
          }
        case 83: break;
        case 11: 
          { new Token(NEQ, yytext(), yyline, yycolumn);
          }
        case 84: break;
        case 4: 
          { 
          }
        case 85: break;
        case 20: 
          { new Token(SEMICOLON, yytext(), yyline, yycolumn);
          }
        case 86: break;
        default: 
          if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
            zzAtEOF = true;
            return YYEOF;
          } 
          else {
            zzScanError(ZZ_NO_MATCH);
          }
      }
    }
  }

  /**
   * Runs the scanner on input files.
   *
   * This is a standalone scanner, it will print any unmatched
   * text to System.out unchanged.
   *
   * @param argv   the command line, contains the filenames to run
   *               the scanner on.
   */
  public static void main(String argv[]) {
    if (argv.length == 0) {
      System.out.println("Usage : java MyScanner <inputfile>");
    }
    else {
      for (int i = 0; i < argv.length; i++) {
        MyScanner scanner = null;
        try {
          scanner = new MyScanner( new java.io.FileReader(argv[i]) );
          while ( !scanner.zzAtEOF ) scanner.yylex();
        }
        catch (java.io.FileNotFoundException e) {
          System.out.println("File not found : \""+argv[i]+"\"");
        }
        catch (java.io.IOException e) {
          System.out.println("IO error scanning file \""+argv[i]+"\"");
          System.out.println(e);
        }
        catch (Exception e) {
          System.out.println("Unexpected exception:");
          e.printStackTrace();
        }
      }
    }
  }


}
