/* The following code was generated by JFlex 1.4.3 on 02.05.12 21:47 */

package haw.ai.ci;

import static haw.ai.ci.TokenID.*;



/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.4.3
 * on 02.05.12 21:47 from the specification file
 * <tt>input/grammar.flex</tt>
 */
public class Scanner {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0, 0
  };

  /** 
   * Translates characters to character classes
   */
  private static final String ZZ_CMAP_PACKED = 
    "\11\0\1\4\1\7\2\0\1\4\22\0\1\4\1\0\1\5\1\16"+
    "\4\0\1\23\1\24\1\10\1\11\1\22\1\12\1\21\1\13\12\1"+
    "\1\14\1\27\1\17\1\15\1\20\2\0\1\47\1\54\1\52\1\36"+
    "\1\34\1\31\1\55\1\33\1\41\2\2\1\43\1\56\1\35\1\30"+
    "\1\37\1\2\1\40\1\44\1\32\1\50\1\53\1\45\1\2\1\51"+
    "\1\2\1\25\1\6\1\26\1\0\1\3\1\0\1\42\1\54\1\52"+
    "\1\36\1\46\1\31\1\55\1\33\1\41\2\2\1\43\1\56\1\35"+
    "\1\30\1\37\1\2\1\40\1\44\1\32\1\50\1\53\1\45\1\2"+
    "\1\51\1\2\uff85\0";

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = zzUnpackCMap(ZZ_CMAP_PACKED);

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\0\1\1\1\2\1\3\1\4\1\1\1\5\1\6"+
    "\1\7\1\10\1\11\1\12\1\13\1\14\1\15\1\16"+
    "\1\17\1\20\1\21\1\22\1\23\1\24\16\3\1\0"+
    "\1\25\1\0\1\26\1\27\1\30\1\31\4\3\1\32"+
    "\2\3\1\33\11\3\1\34\12\3\1\35\2\3\1\36"+
    "\1\37\1\40\4\3\1\41\7\3\1\42\1\3\1\43"+
    "\2\3\1\44\1\45\1\46\1\47\1\50\2\3\1\51"+
    "\1\52\1\53\2\3\1\54";

  private static int [] zzUnpackAction() {
    int [] result = new int[107];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\57\0\136\0\215\0\57\0\274\0\57\0\57"+
    "\0\136\0\57\0\353\0\57\0\57\0\u011a\0\u0149\0\57"+
    "\0\57\0\57\0\57\0\57\0\57\0\57\0\u0178\0\u01a7"+
    "\0\u01d6\0\u0205\0\u0234\0\u0263\0\u0292\0\u02c1\0\u02f0\0\u031f"+
    "\0\u034e\0\u037d\0\u03ac\0\u03db\0\274\0\57\0\u040a\0\57"+
    "\0\57\0\57\0\215\0\u0439\0\u0468\0\u0497\0\u04c6\0\215"+
    "\0\u04f5\0\u0524\0\215\0\u0553\0\u0582\0\u05b1\0\u05e0\0\u060f"+
    "\0\u063e\0\u066d\0\u069c\0\u06cb\0\215\0\u06fa\0\u0729\0\u0758"+
    "\0\u0787\0\u07b6\0\u07e5\0\u0814\0\u0843\0\u0872\0\u08a1\0\215"+
    "\0\u08d0\0\u08ff\0\215\0\215\0\215\0\u092e\0\u095d\0\u098c"+
    "\0\u09bb\0\215\0\u09ea\0\u0a19\0\u0a48\0\u0a77\0\u0aa6\0\u0ad5"+
    "\0\u0b04\0\215\0\u0b33\0\215\0\u0b62\0\u0b91\0\215\0\215"+
    "\0\215\0\215\0\215\0\u0bc0\0\u0bef\0\215\0\215\0\215"+
    "\0\u0c1e\0\u0c4d\0\215";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[107];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\2\1\3\1\4\1\2\1\5\1\6\1\2\1\5"+
    "\1\7\1\10\1\11\1\12\1\13\1\14\1\15\1\16"+
    "\1\17\1\20\1\21\1\22\1\23\1\24\1\25\1\26"+
    "\1\27\1\4\1\30\1\4\1\31\1\4\1\32\1\33"+
    "\1\34\1\35\1\36\2\4\1\37\1\31\1\36\1\40"+
    "\1\4\1\41\1\42\1\43\1\4\1\44\60\0\1\3"+
    "\56\0\3\4\24\0\27\4\5\45\1\46\1\47\50\45"+
    "\15\0\1\50\56\0\1\51\56\0\1\52\42\0\3\4"+
    "\24\0\1\4\1\53\25\4\1\0\3\4\24\0\3\4"+
    "\1\54\15\4\1\55\5\4\1\0\3\4\24\0\5\4"+
    "\1\56\5\4\1\57\13\4\1\0\3\4\24\0\1\60"+
    "\26\4\1\0\3\4\24\0\10\4\1\61\16\4\1\0"+
    "\3\4\24\0\4\4\1\62\11\4\1\62\10\4\1\0"+
    "\3\4\24\0\1\4\1\63\25\4\1\0\3\4\24\0"+
    "\10\4\1\64\16\4\1\0\3\4\24\0\3\4\1\65"+
    "\23\4\1\0\3\4\24\0\5\4\1\66\21\4\1\0"+
    "\3\4\24\0\1\67\26\4\1\0\3\4\24\0\12\4"+
    "\1\70\4\4\1\70\7\4\1\0\3\4\24\0\4\4"+
    "\1\71\11\4\1\71\10\4\1\0\3\4\24\0\1\72"+
    "\26\4\7\45\1\0\47\45\1\0\3\4\24\0\4\4"+
    "\1\73\11\4\1\73\10\4\1\0\3\4\24\0\7\4"+
    "\1\74\17\4\1\0\3\4\24\0\6\4\1\75\20\4"+
    "\1\0\3\4\24\0\14\4\1\76\12\4\1\0\3\4"+
    "\24\0\1\77\10\4\1\100\15\4\1\0\3\4\24\0"+
    "\7\4\1\101\2\4\1\102\4\4\1\102\2\4\1\103"+
    "\4\4\1\0\3\4\24\0\10\4\1\104\16\4\1\0"+
    "\3\4\24\0\11\4\1\105\15\4\1\0\3\4\24\0"+
    "\2\4\1\106\24\4\1\0\3\4\24\0\5\4\1\107"+
    "\21\4\1\0\3\4\24\0\10\4\1\110\16\4\1\0"+
    "\3\4\24\0\25\4\1\111\1\4\1\0\3\4\24\0"+
    "\6\4\1\112\20\4\1\0\3\4\24\0\5\4\1\113"+
    "\21\4\1\0\3\4\24\0\4\4\1\114\11\4\1\114"+
    "\10\4\1\0\3\4\24\0\4\4\1\115\4\4\1\116"+
    "\4\4\1\115\10\4\1\0\3\4\24\0\22\4\1\117"+
    "\4\4\1\0\3\4\24\0\5\4\1\120\21\4\1\0"+
    "\3\4\24\0\4\4\1\121\11\4\1\121\10\4\1\0"+
    "\3\4\24\0\6\4\1\122\20\4\1\0\3\4\24\0"+
    "\1\123\26\4\1\0\3\4\24\0\12\4\1\124\4\4"+
    "\1\124\7\4\1\0\3\4\24\0\13\4\1\125\13\4"+
    "\1\0\3\4\24\0\11\4\1\126\15\4\1\0\3\4"+
    "\24\0\14\4\1\127\12\4\1\0\3\4\24\0\11\4"+
    "\1\130\15\4\1\0\3\4\24\0\20\4\1\131\6\4"+
    "\1\0\3\4\24\0\1\4\1\132\25\4\1\0\3\4"+
    "\24\0\4\4\1\133\11\4\1\133\10\4\1\0\3\4"+
    "\24\0\2\4\1\134\24\4\1\0\3\4\24\0\16\4"+
    "\2\135\7\4\1\0\3\4\24\0\10\4\1\136\16\4"+
    "\1\0\3\4\24\0\21\4\1\137\5\4\1\0\3\4"+
    "\24\0\4\4\1\140\11\4\1\140\10\4\1\0\3\4"+
    "\24\0\13\4\1\141\13\4\1\0\3\4\24\0\2\4"+
    "\1\142\24\4\1\0\3\4\24\0\5\4\1\143\21\4"+
    "\1\0\3\4\24\0\13\4\1\144\13\4\1\0\3\4"+
    "\24\0\6\4\1\145\20\4\1\0\3\4\24\0\2\4"+
    "\1\146\24\4\1\0\3\4\24\0\6\4\1\147\20\4"+
    "\1\0\3\4\24\0\4\4\1\150\11\4\1\150\10\4"+
    "\1\0\3\4\24\0\20\4\1\151\6\4\1\0\3\4"+
    "\24\0\10\4\1\152\16\4\1\0\3\4\24\0\4\4"+
    "\1\153\11\4\1\153\10\4";

  private static int [] zzUnpackTrans() {
    int [] result = new int[3196];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unkown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\0\1\11\2\1\1\11\1\1\2\11\1\1\1\11"+
    "\1\1\2\11\2\1\7\11\16\1\1\0\1\11\1\0"+
    "\3\11\101\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[107];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn;

  /** 
   * zzAtBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;


  /**
   * Creates a new scanner
   * There is also a java.io.InputStream version of this constructor.
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public Scanner(java.io.Reader in) {
    this.zzReader = in;
  }

  /**
   * Creates a new scanner.
   * There is also java.io.Reader version of this constructor.
   *
   * @param   in  the java.io.Inputstream to read input from.
   */
  public Scanner(java.io.InputStream in) {
    this(new java.io.InputStreamReader(in));
  }

  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] zzUnpackCMap(String packed) {
    char [] map = new char[0x10000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 166) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }


  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead-zzStartRead);

      /* translate stored positions */
      zzEndRead-= zzStartRead;
      zzCurrentPos-= zzStartRead;
      zzMarkedPos-= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzCurrentPos*2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
    }

    /* finally: fill the buffer with new input */
    int numRead = zzReader.read(zzBuffer, zzEndRead,
                                            zzBuffer.length-zzEndRead);

    if (numRead > 0) {
      zzEndRead+= numRead;
      return false;
    }
    // unlikely but not impossible: read 0 characters, but not at end of stream    
    if (numRead == 0) {
      int c = zzReader.read();
      if (c == -1) {
        return true;
      } else {
        zzBuffer[zzEndRead++] = (char) c;
        return false;
      }     
    }

	// numRead < 0
    return true;
  }

    
  /**
   * Closes the input stream.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true;            /* indicate end of file */
    zzEndRead = zzStartRead;  /* invalidate buffer    */

    if (zzReader != null)
      zzReader.close();
  }


  /**
   * Resets the scanner to read from a new input stream.
   * Does not close the old reader.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>ZZ_INITIAL</tt>.
   *
   * @param reader   the new input stream 
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzAtBOL  = true;
    zzAtEOF  = false;
    zzEOFDone = false;
    zzEndRead = zzStartRead = 0;
    zzCurrentPos = zzMarkedPos = 0;
    yyline = yychar = yycolumn = 0;
    zzLexicalState = YYINITIAL;
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final String yytext() {
    return new String( zzBuffer, zzStartRead, zzMarkedPos-zzStartRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer[zzStartRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public Token yylex() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char [] zzBufferL = zzBuffer;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      boolean zzR = false;
      for (zzCurrentPosL = zzStartRead; zzCurrentPosL < zzMarkedPosL;
                                                             zzCurrentPosL++) {
        switch (zzBufferL[zzCurrentPosL]) {
        case '\u000B':
        case '\u000C':
        case '\u0085':
        case '\u2028':
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn++;
        }
      }

      if (zzR) {
        // peek one character ahead if it is \n (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof) 
            zzPeek = false;
          else 
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;
  
      zzState = ZZ_LEXSTATE[zzLexicalState];


      zzForAction: {
        while (true) {
    
          if (zzCurrentPosL < zzEndReadL)
            zzInput = zzBufferL[zzCurrentPosL++];
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = zzBufferL[zzCurrentPosL++];
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          int zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
        case 20: 
          { return new Token(SEMICOLON, yytext(), yyline, yycolumn);
          }
        case 45: break;
        case 39: 
          { return new Token(CONST, yytext(), yyline, yycolumn);
          }
        case 46: break;
        case 14: 
          { return new Token(DOT, yytext(), yyline, yycolumn);
          }
        case 47: break;
        case 30: 
          { return new Token(THEN, yytext(), yyline, yycolumn);
          }
        case 48: break;
        case 25: 
          { return new Token(OF, yytext(), yyline, yycolumn);
          }
        case 49: break;
        case 22: 
          { return new Token(ASSIGN, yytext(), yyline, yycolumn);
          }
        case 50: break;
        case 3: 
          { return new Token(IDENT, yytext(), yyline, yycolumn);
          }
        case 51: break;
        case 7: 
          { return new Token(MINUS, yytext(), yyline, yycolumn);
          }
        case 52: break;
        case 16: 
          { return new Token(LPAR, yytext(), yyline, yycolumn);
          }
        case 53: break;
        case 19: 
          { return new Token(RBRAC, yytext(), yyline, yycolumn);
          }
        case 54: break;
        case 23: 
          { return new Token(LOEQ, yytext(), yyline, yycolumn);
          }
        case 55: break;
        case 38: 
          { return new Token(UNTIL, yytext(), yyline, yycolumn);
          }
        case 56: break;
        case 10: 
          { return new Token(EQ, yytext(), yyline, yycolumn);
          }
        case 57: break;
        case 37: 
          { return new Token(WHILE, yytext(), yyline, yycolumn);
          }
        case 58: break;
        case 26: 
          { return new Token(DO, yytext(), yyline, yycolumn);
          }
        case 59: break;
        case 40: 
          { return new Token(BEGIN, yytext(), yyline, yycolumn);
          }
        case 60: break;
        case 24: 
          { return new Token(HIEQ, yytext(), yyline, yycolumn);
          }
        case 61: break;
        case 27: 
          { return new Token(IF, yytext(), yyline, yycolumn);
          }
        case 62: break;
        case 41: 
          { return new Token(REPEAT, yytext(), yyline, yycolumn);
          }
        case 63: break;
        case 8: 
          { return new Token(DIV, yytext(), yyline, yycolumn);
          }
        case 64: break;
        case 12: 
          { return new Token(LO, yytext(), yyline, yycolumn);
          }
        case 65: break;
        case 17: 
          { return new Token(RPAR, yytext(), yyline, yycolumn);
          }
        case 66: break;
        case 9: 
          { return new Token(COLON, yytext(), yyline, yycolumn);
          }
        case 67: break;
        case 33: 
          { return new Token(READ, yytext(), yyline, yycolumn);
          }
        case 68: break;
        case 32: 
          { return new Token(ELSE, yytext(), yyline, yycolumn);
          }
        case 69: break;
        case 2: 
          { return new Token(INT, yytext(), yyline, yycolumn);
          }
        case 70: break;
        case 28: 
          { return new Token(END, yytext(), yyline, yycolumn);
          }
        case 71: break;
        case 34: 
          { return new Token(ELSIF, yytext(), yyline, yycolumn);
          }
        case 72: break;
        case 35: 
          { return new Token(PRINT, yytext(), yyline, yycolumn);
          }
        case 73: break;
        case 31: 
          { return new Token(TYPE, yytext(), yyline, yycolumn);
          }
        case 74: break;
        case 6: 
          { return new Token(PLUS, yytext(), yyline, yycolumn);
          }
        case 75: break;
        case 15: 
          { return new Token(COMMA, yytext(), yyline, yycolumn);
          }
        case 76: break;
        case 44: 
          { return new Token(PROCEDURE, yytext(), yyline, yycolumn);
          }
        case 77: break;
        case 36: 
          { return new Token(ARRAY, yytext(), yyline, yycolumn);
          }
        case 78: break;
        case 5: 
          { return new Token(MUL, yytext(), yyline, yycolumn);
          }
        case 79: break;
        case 1: 
          { return new Token(ERROR, yytext(), yyline, yycolumn);
          }
        case 80: break;
        case 11: 
          { return new Token(NEQ, yytext(), yyline, yycolumn);
          }
        case 81: break;
        case 42: 
          { return new Token(RECORD, yytext(), yyline, yycolumn);
          }
        case 82: break;
        case 43: 
          { return new Token(MODULE, yytext(), yyline, yycolumn);
          }
        case 83: break;
        case 29: 
          { return new Token(VAR, yytext(), yyline, yycolumn);
          }
        case 84: break;
        case 21: 
          { return new Token(STR, yytext(), yyline, yycolumn);
          }
        case 85: break;
        case 13: 
          { return new Token(HI, yytext(), yyline, yycolumn);
          }
        case 86: break;
        case 18: 
          { return new Token(LBRAC, yytext(), yyline, yycolumn);
          }
        case 87: break;
        case 4: 
          { 
          }
        case 88: break;
        default: 
          if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
            zzAtEOF = true;
            return null;
          } 
          else {
            zzScanError(ZZ_NO_MATCH);
          }
      }
    }
  }


}
